// THIS CODE IS USED IN THE DJANGO PROJECT FOR puppeteer (in create_report)
// DO NOT EDIT THIS FILE

const puppeteer = require('puppeteer');

async function run() {
  // Setup
  const browser = await puppeteer.launch({ headless: true });
  const page = await browser.newPage();

  // set the cookie
  await page.setCookie({
      name: 'sessionid',
      value: 'vh8ymk4pf348nife3ia6za7l7fnbqltw',
      domain: 'localhost.dk',
      path: '/',
  });

  // go to the page
  await page.goto('http://localhost.dk:8000/app/reports/pdf/62');

  page.on('console', async function(msg) {
      const successMsg = 'ACCURANKER_LOADED_TIME_TO_SMILE';
      const isDone = msg.text().includes(successMsg);

      if (isDone) {
        await page.pdf({
            path: '3242249c2de241f1a5d63cd08cc86293.pdf',
            format: 'A4',
            scale: 1,
            landscape: true,
        });
        console.log('/files/3242249c2de241f1a5d63cd08cc86293.pdf')
        browser.close();
      }
  });
}

run();
